version: '2'
services:
  db:
    image: postgres:11
    user: root
    container_name: odoo_13_mydb
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo13:
    image: odoo:13
    user: root
    container_name: odoo_13_myserver
    depends_on:
      - db
    ports:
      - "10014:8069"
      - "20014:8072" # live chat
    tty: true
    command: --
#    command: odoo scaffold /mnt/extra-addons/test_module
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./custom-addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always             # run as a service
